# Generated by Django 4.2.2 on 2023-06-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
